force-app/main/default/objects/RRMP_Contact_Info__c/RRMP_Contact_Info__c.object-meta.xml
<CustomObject>
    <label>RRMP Contact Information</label>
    <nameField>
        <displayFormat>RRMP-{0000}</displayFormat>
        <label>RRMP Contact information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RRMP Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RRMP_Contact_Info__c/fields/Screen_Message__c.field-meta.xml
<CustomField>
    <fullName>Screen_Message__c</fullName>
    <label>Screen Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RRMP_Contact_Info__c/recordTypes/RRMP_DI.recordType-meta.xml
<RecordType>
    <fullName>RRMP_DI</fullName>
    <active>true</active>
    <label>RRMP DI</label>
</RecordType>

force-app/main/default/classes/RRMPInfoControllerTest.cls
@istest
public with sharing class RRMPInfoControllerTest {
    //This test will check if a record is successfully found based on type field on the metadata object
    @isTest
    static void getRRMPContactInfoTest(){
        String contactType = 'RRMP_DI';
        RRMP_Contact_Info__c retrivedData = new RRMP_Contact_Info__c(); 
        
        test.startTest();
        retrivedData = RRMPInfoController.getRRMPContactInfo(contactType);
        test.stopTest();
        
        String screenMessage = [SELECT Screen_Message__c FROM RRMP_Contact_Info__c WHERE Name =: contactType LIMIT 1].Screen_Message__c;
        //Negative assert
        system.assertNotEquals(null, retrivedData.Screen_Message__c);
        //Positive assert
        system.assertEquals(screenMessage, retrivedData.Screen_Message__c);
    }
    
    //This test will forcefully feed an null value to catch the error handling when searching for a record
    @isTest
    static void getRRMPContactInfoNullTest(){
        String contactType = null;
        RRMP_Contact_Info__c retrivedData = new RRMP_Contact_Info__c();

        test.startTest();
        retrivedData = RRMPInfoController.getRRMPContactInfo(contactType);
        test.stopTest();
        
        //Negative assert
        system.assertEquals(null, retrivedData);
    }
}